import pytest

from iphasimulator.charmmgui_import import (
    check_cgenff_penalties,
    format_cgenff_penalty_report,
    penalty_category,
    penalty_grade,
    read_cgenff_penalties,
)


HEADER = """* Topologies generated by
* CHARMM General Force Field (CGenFF) program version 4.0
* For use with CGenFF topology and parameter files version 5.0
*
"""

LIG_RTF = HEADER + """36 1

! "penalty" is the highest penalty score of the associated parameters.
RESI lig            0.000 ! param penalty=  12.500 ; charge penalty=   3.529
GROUP            ! CHARGE   CH_PENALTY
ATOM O1     OG311  -0.600 !    2.165
ATOM C1     CG2O2   0.758 !    3.529
ATOM C8     CG331  -0.270 !    0.000

END
"""

LIG_G_RTF = HEADER + """RESI lig            0.000 ! param penalty=  12.500 ; charge penalty=   3.529
GROUP
ATOM    C17  CG2O2   0.9280
"""

LIG_PRM = HEADER + """
DIHEDRALS
OG302  CG2O2  CG321  CG311      0.5300  2   180.00 ! lig , from OG302 CG2O2 CG321 CG321, penalty= 0.6
OG302  CG311  CG321  CG2O2      2.0000  1   180.00 ! lig , from CG2O2 CG311 CG311 OG301, penalty= 12.5

END
"""


@pytest.fixture
def lig_dir(tmp_path):
    (tmp_path / "lig.rtf").write_text(LIG_RTF)
    (tmp_path / "lig_g.rtf").write_text(LIG_G_RTF)
    (tmp_path / "lig.prm").write_text(LIG_PRM)
    return tmp_path


def test_read_cgenff_penalties_parses_all_three_files(lig_dir):
    report = read_cgenff_penalties(lig_dir)

    assert report.files_read == ("lig.rtf", "lig_g.rtf", "lig.prm")
    assert report.program_version == "4.0"
    assert report.parameter_files_version == "5.0"
    assert report.resi_penalties == {"lig.rtf": (12.5, 3.529), "lig_g.rtf": (12.5, 3.529)}
    assert [entry.penalty for entry in report.charge_penalties] == [2.165, 3.529, 0.0]
    assert report.max_charge_penalty == 3.529
    assert report.max_parameter_penalty == 12.5
    assert report.top_charge_penalties(1)[0].label == "C1 (CG2O2, q=0.758)"
    top_parameter = report.top_parameter_penalties(1)[0]
    assert top_parameter.label.startswith("OG302 CG311 CG321 CG2O2")
    assert top_parameter.source == "lig.prm"


def test_read_cgenff_penalties_skips_missing_files(tmp_path):
    (tmp_path / "lig.prm").write_text(LIG_PRM)

    report = read_cgenff_penalties(tmp_path)

    assert report.files_read == ("lig.prm",)
    assert report.max_charge_penalty is None
    assert report.max_parameter_penalty == 12.5


def test_read_cgenff_penalties_requires_at_least_one_file(tmp_path):
    with pytest.raises(FileNotFoundError, match="lig.rtf"):
        read_cgenff_penalties(tmp_path)


@pytest.mark.parametrize(
    ("penalty", "category"),
    [
        (None, "not reported"),
        (4.5, "fair analogy"),
        (10.0, "basic validation recommended"),
        (50.0, "basic validation recommended"),
        (50.1, "extensive validation required"),
    ],
)
def test_penalty_category_uses_cgenff_thresholds(penalty, category):
    assert penalty_category(penalty) == category


def test_format_cgenff_penalty_report_mentions_maxima(lig_dir):
    text = format_cgenff_penalty_report(read_cgenff_penalties(lig_dir), top=2)

    assert "CGenFF program 4.0; topology/parameter files 5.0" in text
    assert "Max charge penalty: 3.529 (fair analogy)" in text
    assert "Max parameter penalty: 12.5 (basic validation recommended)" in text


def test_check_cgenff_penalties_warns_between_10_and_50(lig_dir):
    result = check_cgenff_penalties(lig_dir)

    assert result.status == "WARN"
    assert result.passed
    assert "12.5 / 3.529" in result.evidence


def test_check_cgenff_penalties_skips_without_lig_folder(tmp_path):
    assert check_cgenff_penalties(None).status == "SKIP"
    assert check_cgenff_penalties(tmp_path).status == "SKIP"


@pytest.mark.parametrize("penalty, grade", [(0, "GOOD"), (9.99, "GOOD"), (10, "CHECK"), (50, "CHECK"), (50.1, "POOR")])
def test_penalty_grade(penalty, grade):
    assert penalty_grade(penalty) == grade
