"""CHARMM-GUI → GROMACS helpers on small synthetic systems; gmx is never run."""

import subprocess

import pytest
from rdkit import Chem
from rdkit.Chem import AllChem

from iphasimulator.charmmgui_import import (
    CHARMM_GROMACS_TEMPLATE_DIR,
    check_charmm_defaults,
    check_net_charge,
    format_checks,
    prepare_dry_ligand_folder,
    prepare_charmm_gui_run_folder,
    read_minimization_result,
    run_dry_minimization,
    validate_dry_ligand_folder,
    validate_charmm_gui_run_folder,
)


R_LIGAND = "C[C@@H](O)CC(=O)O"  # (R)-3-hydroxybutanoic acid
S_LIGAND = "C[C@H](O)CC(=O)O"
TYPE_BY_ELEMENT = {"C": "CG321", "O": "OG311", "H": "HGA2"}
MASS_BY_ELEMENT = {"C": 12.011, "O": 15.9994, "H": 1.008}

FORCEFIELD_ITP = """[ defaults ]
; nbfunc	comb-rule	gen-pairs	fudgeLJ	fudgeQQ
1	2	yes	1.0	1.0
"""
TIP3_ITP = """[ moleculetype ]
TIP3 2
[ atoms ]
1 OT 1 TIP3 OH2 1 -0.834 15.9994
2 HT 1 TIP3 H1 2 0.417 1.008
3 HT 1 TIP3 H2 3 0.417 1.008
"""
IONS_ITP = """[ moleculetype ]
SOD 0
[ atoms ]
1 SOD 1 SOD SOD 1 1.000 22.98977
[ moleculetype ]
CLA 0
[ atoms ]
1 CLA 1 CLA CLA 1 -1.000 35.45
"""


def _embedded(smiles):
    mol = Chem.AddHs(Chem.MolFromSmiles(smiles))
    AllChem.EmbedMolecule(mol, randomSeed=7)
    return mol


def _ligand_itp(mol, types=None):
    names = [f"{atom.GetSymbol()}{atom.GetIdx() + 1}" for atom in mol.GetAtoms()]
    lines = ["[ moleculetype ]", "LIG 3", "[ atoms ]"]
    for atom, name in zip(mol.GetAtoms(), names):
        element = atom.GetSymbol()
        atom_type = (types or TYPE_BY_ELEMENT)[element]
        lines.append(
            f"{atom.GetIdx() + 1} {atom_type} 1 LIG {name} {atom.GetIdx() + 1} 0.000 {MASS_BY_ELEMENT[element]}"
        )
    lines.append("[ bonds ]")
    lines += [f"{bond.GetBeginAtomIdx() + 1} {bond.GetEndAtomIdx() + 1} 1" for bond in mol.GetBonds()]
    return "\n".join(lines) + "\n", names


def _gro_line(residue_number, residue, name, index, xyz_nm):
    x, y, z = xyz_nm
    return f"{residue_number:5d}{residue:<5}{name:>5}{index:5d}{x:8.3f}{y:8.3f}{z:8.3f}"


def _write_solution_builder(folder, smiles=R_LIGAND, wrap_first_atom=False):
    """A tiny Solution Builder-like gromacs/ folder: LIG + 1 TIP3 + SOD + CLA."""

    gromacs = folder / "gromacs"
    (gromacs / "toppar").mkdir(parents=True)
    ligand = _embedded(smiles)
    itp, names = _ligand_itp(ligand)
    (gromacs / "toppar" / "forcefield.itp").write_text(FORCEFIELD_ITP)
    (gromacs / "toppar" / "LIG.itp").write_text(itp)
    (gromacs / "toppar" / "TIP3.itp").write_text(TIP3_ITP)
    (gromacs / "toppar" / "ions.itp").write_text(IONS_ITP)
    (gromacs / "topol.top").write_text(
        '#include "toppar/forcefield.itp"\n#include "toppar/LIG.itp"\n'
        '#include "toppar/TIP3.itp"\n#include "toppar/ions.itp"\n'
        "[ system ]\nTitle\n[ molecules ]\nLIG 1\nTIP3 1\nSOD 1\nCLA 1\n"
    )
    box = 3.0
    positions = ligand.GetConformer().GetPositions() / 10 + 1.5
    if wrap_first_atom:
        positions[0][0] += box  # molecule split across the periodic boundary
    lines = [_gro_line(1, "LIG", name, i + 1, xyz) for i, (name, xyz) in enumerate(zip(names, positions))]
    n = len(lines)
    lines += [
        _gro_line(2, "TIP3", "OH2", n + 1, (0.2, 0.2, 0.2)),
        _gro_line(2, "TIP3", "H1", n + 2, (0.3, 0.2, 0.2)),
        _gro_line(2, "TIP3", "H2", n + 3, (0.2, 0.3, 0.2)),
        _gro_line(3, "SOD", "SOD", n + 4, (2.5, 2.5, 2.5)),
        _gro_line(4, "CLA", "CLA", n + 5, (2.5, 0.5, 2.5)),
    ]
    (gromacs / "step3_input.gro").write_text(
        "Generated by test\n" + f"{len(lines):5d}\n" + "\n".join(lines) + f"\n{box:10.5f}{box:10.5f}{box:10.5f}\n"
    )
    (gromacs / "index.ndx").write_text(f"[ SOLU ]\n{' '.join(str(i) for i in range(1, n + 1))}\n[ SOLV ]\n{n + 1} {n + 2} {n + 3}\n")
    (gromacs / "step4.0_minimization.mdp").write_text("integrator = steep\n")
    (gromacs / "step5_production.mdp").write_text("integrator = md\n")
    sdf = folder / "ligand.sdf"
    Chem.MolToMolFile(_embedded(R_LIGAND), str(sdf))
    return folder, sdf


def _status(results, prefix):
    return next(result.status for result in results if result.name.startswith(prefix))


def test_prepare_charmm_gui_run_folder_follows_production_layout(tmp_path):
    download, _ = _write_solution_builder(tmp_path / "download")

    run = prepare_charmm_gui_run_folder(download, tmp_path / "run", job_name="PHO4_GK13")

    assert (run / "step5_input.gro").is_file()
    assert not (run / "step3_input.gro").exists()
    assert not (run / "step4.0_minimization.mdp").exists()
    assert not (run / "step5_production.mdp").exists()
    assert (run / "toppar" / "LIG.itp").is_file()
    for name in ("step6.0_minimization.mdp", "step6.1_nvt.mdp", "step6.2_npt.mdp", "step7_production.mdp"):
        assert (run / name).read_text() == (CHARMM_GROMACS_TEMPLATE_DIR / name).read_text()
    slurm = (run / "run_hpc_equilibration_production.slurm").read_text()
    assert "#SBATCH --job-name=PHO4_GK13" in slurm
    assert "{JOB_NAME}" not in slurm
    assert (download / "gromacs" / "step3_input.gro").is_file()  # source untouched


def test_validate_charmm_gui_run_folder_passes_for_consistent_system(tmp_path):
    download, sdf = _write_solution_builder(tmp_path / "download")
    run = prepare_charmm_gui_run_folder(download, tmp_path / "run")

    results = validate_charmm_gui_run_folder(run, sdf_path=sdf)

    assert all(result.status == "PASS" for result in results), format_checks(results)
    assert format_checks(results).endswith("Overall: PASS")


def test_stereocentre_check_survives_molecule_split_across_box(tmp_path):
    download, sdf = _write_solution_builder(tmp_path / "download", wrap_first_atom=True)
    run = prepare_charmm_gui_run_folder(download, tmp_path / "run")

    results = validate_charmm_gui_run_folder(run, sdf_path=sdf)

    assert _status(results, "LIG stereocentres") == "PASS"


def test_stereocentre_check_fails_for_s_ligand(tmp_path):
    download, _ = _write_solution_builder(tmp_path / "download", smiles=S_LIGAND)
    sdf = tmp_path / "s.sdf"
    Chem.MolToMolFile(_embedded(S_LIGAND), str(sdf))
    run = prepare_charmm_gui_run_folder(download, tmp_path / "run")

    results = validate_charmm_gui_run_folder(run, sdf_path=sdf)

    assert _status(results, "LIG stereocentres") == "FAIL"
    assert "S" in next(r.evidence for r in results if r.name.startswith("LIG stereocentres"))


def test_stereocentre_check_skips_without_sdf(tmp_path):
    download, _ = _write_solution_builder(tmp_path / "download")
    run = prepare_charmm_gui_run_folder(download, tmp_path / "run")

    assert _status(validate_charmm_gui_run_folder(run), "LIG stereocentres") == "SKIP"


def test_checks_fail_for_broken_topology(tmp_path):
    download, sdf = _write_solution_builder(tmp_path / "download")
    run = prepare_charmm_gui_run_folder(download, tmp_path / "run")
    (run / "toppar" / "forcefield.itp").write_text("[ defaults ]\n1 2 yes 0.5 0.8333\n")
    (run / "toppar" / "ions.itp").write_text(IONS_ITP.replace("-1.000", "-2.000"))
    lig = run / "toppar" / "LIG.itp"
    lig.write_text(lig.read_text().replace("CG321", "c3", 1))
    (run / "index.ndx").write_text("[ System ]\n1\n")

    results = validate_charmm_gui_run_folder(run, sdf_path=sdf)

    for prefix in ("[ defaults ]", "net charge", "LIG atom types", "run files"):
        assert _status(results, prefix) == "FAIL", prefix
    assert "c3" in next(r.evidence for r in results if r.name.startswith("LIG atom types"))
    assert "SOLU" in next(r.evidence for r in results if r.name.startswith("run files"))


def test_atom_order_check_detects_reordered_ligand(tmp_path):
    download, sdf = _write_solution_builder(tmp_path / "download")
    run = prepare_charmm_gui_run_folder(download, tmp_path / "run")
    lines = (run / "step5_input.gro").read_text().splitlines()
    lines[2], lines[3] = lines[3], lines[2]
    (run / "step5_input.gro").write_text("\n".join(lines) + "\n")

    results = validate_charmm_gui_run_folder(run, sdf_path=sdf)

    assert _status(results, "LIG atom names/order") == "FAIL"


def test_prepare_charmm_gui_run_folder_refuses_existing_or_nested_output(tmp_path):
    download, _ = _write_solution_builder(tmp_path / "download")
    (tmp_path / "exists").mkdir()

    with pytest.raises(FileExistsError):
        prepare_charmm_gui_run_folder(download, tmp_path / "exists")
    with pytest.raises(ValueError, match="Refusing"):
        prepare_charmm_gui_run_folder(download, download / "gromacs" / "run")


def test_prepare_charmm_gui_run_folder_uses_custom_templates(tmp_path):
    download, _ = _write_solution_builder(tmp_path / "download")
    templates = tmp_path / "mine"
    templates.mkdir()
    for name in ("step6.0_minimization.mdp", "step6.1_nvt.mdp", "step6.2_npt.mdp", "step7_production.mdp",
                 "run_step6_local.sh", "run_hpc_equilibration_production.slurm"):
        (templates / name).write_text(f"; my {name}\n")

    run = prepare_charmm_gui_run_folder(download, tmp_path / "run", template_dir=templates)

    assert (run / "step6.1_nvt.mdp").read_text() == "; my step6.1_nvt.mdp\n"
    assert (run / "run_hpc_equilibration_production.slurm").read_text().startswith("; my")


def _write_ligand_reader(folder, smiles=R_LIGAND):
    (folder / "gromacs").mkdir(parents=True)
    ligand = _embedded(smiles)
    itp, names = _ligand_itp(ligand)
    (folder / "gromacs" / "charmm36.itp").write_text(FORCEFIELD_ITP)
    (folder / "gromacs" / "LIG.itp").write_text(itp)
    (folder / "gromacs" / "topol.top").write_text(
        '#include "charmm36.itp"\n#include "LIG.itp"\n[ system ]\nTitle\n[ molecules ]\nLIG 1\n'
    )
    pdb = []
    for index, (name, (x, y, z)) in enumerate(zip(names, ligand.GetConformer().GetPositions()), start=1):
        pdb.append(f"ATOM  {index:5d} {name:<4} LIG L   1    {x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00      LIG")
    (folder / "ligandrm.pdb").write_text("\n".join(pdb) + "\nEND\n")
    sdf = folder / "ligand.sdf"
    Chem.MolToMolFile(ligand, str(sdf))
    return folder, sdf


def test_prepare_and_validate_dry_ligand_folder(tmp_path):
    download, sdf = _write_ligand_reader(tmp_path / "lrm")

    dry = prepare_dry_ligand_folder(download, tmp_path / "dry", padding_nm=1.7)

    assert {p.name for p in dry.iterdir()} == {"topol.top", "charmm36.itp", "LIG.itp", "lig.gro", "dry_minimization.mdp"}
    box = float((dry / "lig.gro").read_text().splitlines()[-1].split()[0])
    assert box > 3.4  # molecule extent + 2 * padding
    results = validate_dry_ligand_folder(dry, sdf_path=sdf)
    assert all(result.status == "PASS" for result in results), format_checks(results)


MDRUN_LOG_TAIL = """
Steepest Descents converged to Fmax < 100 in 212 steps
Potential Energy  = -1.2345678e+02
Maximum force     =  9.8765432e+01 on atom 12
Norm of force     =  2.0000000e+01
"""


def test_run_dry_minimization_calls_grompp_then_mdrun_and_reads_log(tmp_path):
    download, _ = _write_ligand_reader(tmp_path / "lrm")
    dry = prepare_dry_ligand_folder(download, tmp_path / "dry")
    calls = []

    def fake_runner(command, cwd, **kwargs):
        calls.append(command[:2])
        if command[1] == "mdrun":
            (cwd / "dry_minimization.log").write_text(MDRUN_LOG_TAIL)
        return subprocess.CompletedProcess(command, 0, "", "")

    result = run_dry_minimization(dry, runner=fake_runner)

    assert calls == [["gmx", "grompp"], ["gmx", "mdrun"]]
    assert result.potential_energy == pytest.approx(-123.45678)
    assert result.maximum_force == pytest.approx(98.765432)


def test_run_dry_minimization_reports_gmx_failure(tmp_path):
    download, _ = _write_ligand_reader(tmp_path / "lrm")
    dry = prepare_dry_ligand_folder(download, tmp_path / "dry")

    def failing_runner(command, cwd, **kwargs):
        return subprocess.CompletedProcess(command, 1, "", "Fatal error: something")

    with pytest.raises(RuntimeError, match="Fatal error"):
        run_dry_minimization(dry, runner=failing_runner)


def test_read_minimization_result_handles_missing_values(tmp_path):
    log = tmp_path / "md.log"
    log.write_text("no summary here\n")

    result = read_minimization_result(log)

    assert result.potential_energy is None and result.maximum_force is None


def test_single_checks_report_evidence(tmp_path):
    top = tmp_path / "topol.top"
    top.write_text(FORCEFIELD_ITP + IONS_ITP + "[ molecules ]\nSOD 2\nCLA 1\n")

    assert check_charmm_defaults(top).status == "PASS"
    charge = check_net_charge(top)
    assert charge.status == "FAIL"
    assert "+1.0000" in charge.evidence


def test_prepared_run_folder_is_writable_when_download_is_read_only(tmp_path):
    download, _ = _write_solution_builder(tmp_path / "download")
    toppar = download / "gromacs" / "toppar"
    for path in toppar.iterdir():
        path.chmod(0o444)
    toppar.chmod(0o555)
    try:
        run = prepare_charmm_gui_run_folder(download, tmp_path / "run")
        (run / "toppar" / "LIG.itp").write_text("editable\n")
        (run / "toppar" / "new.itp").write_text("")
    finally:
        toppar.chmod(0o755)
        for path in toppar.iterdir():
            path.chmod(0o644)
